# Generated by Django 4.2.6 on 2023-10-13 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
            },
        ),
        migrations.CreateModel(
            name="FeedHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_data", models.TextField(verbose_name="Request data")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=90, verbose_name="Title")),
                (
                    "slug",
                    models.SlugField(max_length=90, unique=True, verbose_name="Slug"),
                ),
                (
                    "markup",
                    models.CharField(
                        choices=[("markdown", "Markdown")],
                        max_length=25,
                        verbose_name="Markup",
                    ),
                ),
                ("teaser_html", models.TextField(editable=False)),
                ("content_html", models.TextField(editable=False)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Updated"
                    ),
                ),
                (
                    "published",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published"
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[(1, "Draft"), (2, "Published")],
                        default=1,
                        verbose_name="State",
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True,
                        help_text="allows url for sharing unpublished posts to unauthenticated users",
                        max_length=8,
                        unique=True,
                        verbose_name="Secret key",
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="View count"
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ("-published",),
                "get_latest_by": "published",
            },
        ),
        migrations.CreateModel(
            name="ReviewComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_text", models.TextField(verbose_name="Review text")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                (
                    "addressed",
                    models.BooleanField(default=False, verbose_name="Addressed"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=90, verbose_name="Title")),
                ("teaser", models.TextField(verbose_name="Teaser")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated"
                    ),
                ),
                (
                    "published",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published"
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="View count"
                    ),
                ),
            ],
            options={
                "verbose_name": "Revision",
                "verbose_name_plural": "Revisions",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
            },
        ),
    ]
