# Generated by Django 4.2.6 on 2023-10-17 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_id_alter_feedhit_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Các mục'},
        ),
        migrations.AlterField(
            model_name='feedhit',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Đã tạo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Đã tạo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả chi tiết '),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Đã xuất bản'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=90, unique=True, verbose_name='Tiêu đề '),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=1, verbose_name='Tiểu bang'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=90, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Đã xuất bản'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='title',
            field=models.CharField(max_length=90, verbose_name='Tiêu đề'),
        ),
    ]
