# Generated by Django 4.2.6 on 2023-10-17 15:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0002_alter_attributeoption_options_and_more'),
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrecord',
            options={'ordering': ['-num_purchases'], 'verbose_name': 'Lịch sử mua hàng', 'verbose_name_plural': 'Những lịch sử mua hàng'},
        ),
        migrations.AlterModelOptions(
            name='userproductview',
            options={'ordering': ['-pk'], 'verbose_name': 'Lượng người xem qua sản phẩm', 'verbose_name_plural': 'Những lần người dùng xem sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='userrecord',
            options={'verbose_name': 'Lịch sử người dùng', 'verbose_name_plural': 'Những lịch sử người dùng'},
        ),
        migrations.AlterModelOptions(
            name='usersearch',
            options={'ordering': ['-pk'], 'verbose_name': 'Dữ liệu người dùng tìm kiếm', 'verbose_name_plural': 'Những yêu cầu tìm kiếm của người '},
        ),
        migrations.AlterField(
            model_name='productrecord',
            name='num_basket_additions',
            field=models.PositiveIntegerField(default=0, verbose_name='Thêm vào giỏ hàng'),
        ),
        migrations.AlterField(
            model_name='productrecord',
            name='num_purchases',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Mua'),
        ),
        migrations.AlterField(
            model_name='productrecord',
            name='num_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Lượng người xem'),
        ),
        migrations.AlterField(
            model_name='productrecord',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='catalogue.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='productrecord',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='Điểm tích lũy'),
        ),
        migrations.AlterField(
            model_name='userproductview',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày tạo '),
        ),
        migrations.AlterField(
            model_name='userproductview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='userproductview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tên khách hàng'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='date_last_order',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Đơn hàng gần nhất'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='num_basket_additions',
            field=models.PositiveIntegerField(default=0, verbose_name='Thêm vào giỏ hàng'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='num_order_items',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sản phẩm đặt hàng'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='num_order_lines',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Dòng đặt hàng'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='num_orders',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Đặt hàng'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='num_product_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Lượt xem sản phẩm'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tổng thành tiền'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tên khách hàng'),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày tạo '),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='query',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Giới hạn tìm kiếm '),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tên khách hàng'),
        ),
    ]
