# Generated by Django 4.2.6 on 2023-10-17 15:32

import creme.creme_core.models.fields.autoslugfield
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationeventtype',
            options={'ordering': ['name'], 'verbose_name': 'Truyền thông kiểu sự kiện', 'verbose_name_plural': 'Truyền thông kiểu sự kiện'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-date_sent'], 'verbose_name': 'Email ', 'verbose_name_plural': 'Email '},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-date_sent',), 'verbose_name': 'Thông báo ', 'verbose_name_plural': 'Những thông báo '},
        ),
        migrations.AlterField(
            model_name='communicationeventtype',
            name='category',
            field=models.CharField(choices=[('Order related', 'Đơn hàng liên quan '), ('User related', 'Khách hàng có liên quan ')], default='Order related', max_length=255, verbose_name='Danh mục '),
        ),
        migrations.AlterField(
            model_name='communicationeventtype',
            name='code',
            field=creme.creme_core.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, help_text='Mã khách hàng dùng cho chương trình tìm kiếm ', max_length=128, populate_from='name', separator='_', unique=True, validators=[django.core.validators.RegexValidator(message="Code can only contain the uppercase letters (A-Z), digits, and underscores, and can't start with a digit.", regex='^[A-Z_][0-9A-Z_]*$')], verbose_name='Mã '),
        ),
        migrations.AlterField(
            model_name='communicationeventtype',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày tạo '),
        ),
        migrations.AlterField(
            model_name='communicationeventtype',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật '),
        ),
        migrations.AlterField(
            model_name='communicationeventtype',
            name='email_body_html_template',
            field=models.TextField(blank=True, help_text='Mẫu HTML ', null=True, verbose_name='Nội dung mẫu HTML '),
        ),
        migrations.AlterField(
            model_name='communicationeventtype',
            name='email_body_template',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung mẫu email '),
        ),
        migrations.AlterField(
            model_name='communicationeventtype',
            name='email_subject_template',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề mẫu email '),
        ),
        migrations.AlterField(
            model_name='communicationeventtype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='communicationeventtype',
            name='sms_template',
            field=models.CharField(blank=True, help_text='Mẫu SMS ', max_length=170, null=True, verbose_name='Mẫu SMS '),
        ),
        migrations.AlterField(
            model_name='email',
            name='body_html',
            field=models.TextField(blank=True, verbose_name='Body HTML '),
        ),
        migrations.AlterField(
            model_name='email',
            name='body_text',
            field=models.TextField(verbose_name='Thông tin '),
        ),
        migrations.AlterField(
            model_name='email',
            name='date_sent',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày gửi '),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Địa chỉ email'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.TextField(max_length=255, verbose_name='Chủ đề '),
        ),
        migrations.AlterField(
            model_name='email',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL, verbose_name='Tên khách hàng'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='location',
            field=models.CharField(choices=[('Inbox', 'Thư đến '), ('Archive', 'Lưu trữ ')], default='Inbox', max_length=32),
        ),
    ]
