# Generated by Django 4.2.6 on 2023-10-13 14:33

import creme.creme_core.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creme_core", "0005_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurrentGenerator",
            fields=[
                (
                    "cremeentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="creme_core.cremeentity",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name of the generator"
                    ),
                ),
                (
                    "first_generation",
                    models.DateTimeField(verbose_name="Date of the first generation"),
                ),
                (
                    "last_generation",
                    models.DateTimeField(
                        editable=False,
                        null=True,
                        verbose_name="Date of the last generation",
                    ),
                ),
                (
                    "periodicity",
                    creme.creme_core.models.fields.DatePeriodField(
                        verbose_name="Periodicity of the generation"
                    ),
                ),
                (
                    "is_working",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="Active ?"
                    ),
                ),
                (
                    "ct",
                    creme.creme_core.models.fields.CTypeForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Type of the recurrent resource",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_set",
                        to="creme_core.cremeentity",
                        verbose_name="Related model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurrent generator",
                "verbose_name_plural": "Recurrent generators",
                "ordering": ("name",),
                "abstract": False,
                "swappable": "RECURRENTS_RGENERATOR_MODEL",
            },
            bases=("creme_core.cremeentity",),
        ),
    ]
