# Generated by Django 4.2.6 on 2023-10-13 14:33

import creme.creme_core.models.deletion
import creme.creme_core.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creme_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Origin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_custom", models.BooleanField(default=True)),
                ("extra_data", models.JSONField(default=dict, editable=False)),
                ("name", models.CharField(max_length=100, verbose_name="Origin")),
            ],
            options={
                "verbose_name": "Origin of opportunity",
                "verbose_name_plural": "Origins of opportunity",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SalesPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_custom", models.BooleanField(default=True)),
                ("extra_data", models.JSONField(default=dict, editable=False)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "order",
                    creme.creme_core.models.fields.BasicAutoField(
                        blank=True, editable=False
                    ),
                ),
                (
                    "color",
                    creme.creme_core.models.fields.ColorField(
                        default=creme.creme_core.models.fields.ColorField.random,
                        max_length=6,
                        verbose_name="Color",
                    ),
                ),
                ("won", models.BooleanField(default=False, verbose_name="Won")),
                ("lost", models.BooleanField(default=False, verbose_name="Lost")),
            ],
            options={
                "verbose_name": "Sale phase",
                "verbose_name_plural": "Sale phases",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "cremeentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="creme_core.cremeentity",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Name of the opportunity"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Reference"
                    ),
                ),
                (
                    "estimated_sales",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Estimated sales"
                    ),
                ),
                (
                    "made_sales",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Made sales"
                    ),
                ),
                (
                    "chance_to_win",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="% of chance to win"
                    ),
                ),
                (
                    "expected_closing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected closing date"
                    ),
                ),
                (
                    "closing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Actual closing date"
                    ),
                ),
                (
                    "first_action_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of the first action"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="creme_core.currency",
                        verbose_name="Currency",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=creme.creme_core.models.deletion.CREME_REPLACE_NULL,
                        to="opportunities.origin",
                        verbose_name="Origin",
                    ),
                ),
                (
                    "sales_phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="opportunities.salesphase",
                        verbose_name="Sales phase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity",
                "verbose_name_plural": "Opportunities",
                "ordering": ("name",),
                "abstract": False,
                "swappable": "OPPORTUNITIES_OPPORTUNITY_MODEL",
            },
            bases=("creme_core.cremeentity",),
        ),
    ]
