# Generated by Django 4.2.6 on 2023-10-17 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creme_core', '0061_alter_currency_options_alter_buttonmenuitem_order_and_more'),
        ('opportunities', '0002_alter_origin_id_alter_salesphase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='creme_core.currency', verbose_name='Tiền tệ'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='tài liêu tham khảo'),
        ),
        migrations.AlterField(
            model_name='salesphase',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên'),
        ),
    ]
