# Generated by Django 4.2.6 on 2023-10-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Assigned", "Assigned"),
                            ("Pending", "Pending"),
                            ("Closed", "Closed"),
                            ("Rejected", "Rejected"),
                            ("Duplicate", "Duplicate"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Normal", "Normal"),
                            ("High", "High"),
                            ("Urgent", "Urgent"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Question", "Question"),
                            ("Incident", "Incident"),
                            ("Problem", "Problem"),
                        ],
                        default="",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("closed_on", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_on",
                    models.DateTimeField(auto_now=True, verbose_name="Created on"),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
