# Generated by Django 4.2.6 on 2023-10-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("creme_core", "0001_initial"),
        ("cases", "0001_initial"),
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts_cases",
                to="creme_core.account",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="assigned_to",
            field=models.ManyToManyField(
                related_name="case_assigned_users", to="userprofile.profile"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="contacts",
            field=models.ManyToManyField(to="contacts.contact"),
        ),
        migrations.AddField(
            model_name="case",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="case_created_by",
                to="userprofile.profile",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="case_org",
                to="userprofile.org",
            ),
        ),
    ]
