# Generated by Django 4.2.6 on 2023-10-13 14:33

import creme.creme_core.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creme_core", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Graph",
            fields=[
                (
                    "cremeentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="creme_core.cremeentity",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of the graph"),
                ),
                (
                    "orbital_relation_types",
                    models.ManyToManyField(
                        editable=False,
                        to="creme_core.relationtype",
                        verbose_name="Types of the peripheral relations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Graph",
                "verbose_name_plural": "Graphs",
                "ordering": ("name",),
                "abstract": False,
                "swappable": "GRAPHS_GRAPH_MODEL",
            },
            bases=("creme_core.cremeentity",),
        ),
        migrations.CreateModel(
            name="RootNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creme_core.cremeentity",
                    ),
                ),
                (
                    "entity_ctype",
                    creme.creme_core.models.fields.EntityCTypeForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roots",
                        to=settings.GRAPHS_GRAPH_MODEL,
                    ),
                ),
                (
                    "relation_types",
                    models.ManyToManyField(
                        editable=False, to="creme_core.relationtype"
                    ),
                ),
            ],
        ),
    ]
