# Generated by Django 4.2.6 on 2023-10-17 11:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speakers', '0003_alter_speaker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Đã tạo'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(help_text='As you would like it to appear in the conference program.', max_length=100, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tên khách hàng'),
        ),
    ]
