# Generated by Django 4.2.6 on 2023-10-17 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0002_alter_attributeoption_options_and_more'),
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['pk'], 'verbose_name': 'Dòng danh sách mong muốn'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ('owner', 'date_created'), 'verbose_name': 'Danh sách mong muốn'},
        ),
        migrations.AlterField(
            model_name='line',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlists_lines', to='catalogue.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='line',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='line',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wishlists.wishlist', verbose_name='Danh sách mong muốn'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_created',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='key',
            field=models.CharField(db_index=True, editable=False, max_length=6, unique=True, verbose_name='Chìa khóa '),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(default='Mặc định', max_length=255, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='Chủ sở hữu'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Riêng tư - Chỉ chủ sử hữu có thể nhìn thấy danh sách mong muốn'), ('Shared', 'Chia sẻ - Chỉ người chủ sở hữu và những người có quyền truy cập vào các liên kết phức tạp có thể nhìn thấy danh sách mong muốn'), ('Public', 'Công khai - Mọi người có thể nhìn thấy danh sách mong muốn')], default='Private', max_length=20, verbose_name='Tầm nhìn'),
        ),
        migrations.AlterField(
            model_name='wishlistsharedemail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email '),
        ),
        migrations.AlterField(
            model_name='wishlistsharedemail',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_emails', to='wishlists.wishlist', verbose_name='Danh sách mong muốn'),
        ),
    ]
