# Generated by Django 4.2.6 on 2023-10-13 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoAddress",
            fields=[
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.PERSONS_ADDRESS_MODEL,
                        verbose_name="Address",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
                (
                    "draggable",
                    models.BooleanField(
                        default=True, verbose_name="Is this marker draggable in maps?"
                    ),
                ),
                (
                    "geocoded",
                    models.BooleanField(
                        default=False, verbose_name="Geocoded from address?"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Not localized"),
                            (1, "Manual location"),
                            (2, "Partially matching location"),
                            (3, ""),
                        ],
                        default=0,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "ordering": ("address_id",),
            },
        ),
        migrations.CreateModel(
            name="Town",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of the town"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, verbose_name="Slugified name of the town"
                    ),
                ),
                (
                    "zipcode",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Zip code"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=40, verbose_name="Country"),
                ),
                ("latitude", models.FloatField(verbose_name="Latitude")),
                ("longitude", models.FloatField(verbose_name="Longitude")),
            ],
            options={
                "verbose_name": "Town",
                "verbose_name_plural": "Towns",
                "ordering": ("name",),
            },
        ),
    ]
