# Generated by Django 4.2.6 on 2023-10-17 18:20

import creme.creme_core.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[creme.creme_core.core.validators.non_whitespace],
                verbose_name="Title",
            ),
        ),
    ]
