# Generated by Django 4.2.6 on 2023-10-17 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.CharField(max_length=100, verbose_name='mô tả'),
        ),
        migrations.AlterField(
            model_name='bookmarkinstance',
            name='description',
            field=models.CharField(max_length=100, verbose_name='mô tả'),
        ),
        migrations.AlterField(
            model_name='bookmarkinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='người dùng'),
        ),
    ]
