# Generated by Django 4.2.6 on 2023-10-13 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creme_core", "0001_initial"),
        migrations.swappable_dependency(settings.EVENTS_EVENT_MODEL),
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachments",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attachment_created_by",
                to="userprofile.profile",
            ),
        ),
        migrations.AddField(
            model_name="attachments",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_attachment",
                to=settings.EVENTS_EVENT_MODEL,
            ),
        ),
    ]
