# Generated by Django 4.2.6 on 2023-10-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creme_core', '0009_alter_user_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='accountdeletion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brickdetailviewlocation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brickhomelocation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brickmypagelocation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brickstate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='buttonmenuitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='casesensitivity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cremeentity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cremeproperty',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customfieldboolean',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customfielddate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customfielddatetime',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customfieldenum',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customfieldenumvalue',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customfieldfloat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customfieldinteger',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customfieldmultienum',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customfieldstring',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customfieldtext',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customfieldurl',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customformconfigitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datereminder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entityfiltercondition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entityjobresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fileref',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historyconfigitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historyline',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imprint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='instancebrickconfigitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='massimportjobresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menuconfigitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passwordexpiry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relationbrickitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='searchconfigitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='semifixedrelationtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='setcredentials',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='settingvalue',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='signupcode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='signupcoderesult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('', 'Language of your browser'), ('vi', 'Tiếng Việt'), ('en', 'English'), ('fr', 'Français'), ('ja', 'Japanese'), ('ko', 'Korean'), ('de', 'German'), ('ru', 'Russian')], default='', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_zone',
            field=models.CharField(choices=[('Pacific/Kanton', 'Pacific/Kanton'), ('America/Indiana/Marengo', 'America/Indiana/Marengo'), ('America/Swift_Current', 'America/Swift_Current'), ('Etc/GMT-1', 'Etc/GMT-1'), ('GB-Eire', 'GB-Eire'), ('Europe/Kirov', 'Europe/Kirov'), ('Pacific/Samoa', 'Pacific/Samoa'), ('America/Scoresbysund', 'America/Scoresbysund'), ('Africa/Banjul', 'Africa/Banjul'), ('America/Danmarkshavn', 'America/Danmarkshavn'), ('Europe/Oslo', 'Europe/Oslo'), ('Brazil/West', 'Brazil/West'), ('Africa/Dar_es_Salaam', 'Africa/Dar_es_Salaam'), ('Asia/Damascus', 'Asia/Damascus'), ('America/Maceio', 'America/Maceio'), ('Africa/Kigali', 'Africa/Kigali'), ('Asia/Dacca', 'Asia/Dacca'), ('Asia/Seoul', 'Asia/Seoul'), ('Europe/Luxembourg', 'Europe/Luxembourg'), ('Australia/Perth', 'Australia/Perth'), ('Indian/Antananarivo', 'Indian/Antananarivo'), ('America/Creston', 'America/Creston'), ('Etc/GMT-11', 'Etc/GMT-11'), ('America/Mazatlan', 'America/Mazatlan'), ('Asia/Yekaterinburg', 'Asia/Yekaterinburg'), ('America/Guyana', 'America/Guyana'), ('Brazil/DeNoronha', 'Brazil/DeNoronha'), ('Africa/Niamey', 'Africa/Niamey'), ('Etc/UTC', 'Etc/UTC'), ('Africa/Mogadishu', 'Africa/Mogadishu'), ('Asia/Muscat', 'Asia/Muscat'), ('Pacific/Nauru', 'Pacific/Nauru'), ('America/Menominee', 'America/Menominee'), ('Atlantic/Reykjavik', 'Atlantic/Reykjavik'), ('EST5EDT', 'EST5EDT'), ('UTC', 'UTC'), ('Antarctica/DumontDUrville', 'Antarctica/DumontDUrville'), ('Asia/Chita', 'Asia/Chita'), ('America/Anguilla', 'America/Anguilla'), ('GMT+0', 'GMT+0'), ('Asia/Dushanbe', 'Asia/Dushanbe'), ('Asia/Macao', 'Asia/Macao'), ('America/Goose_Bay', 'America/Goose_Bay'), ('America/Yakutat', 'America/Yakutat'), ('Europe/Brussels', 'Europe/Brussels'), ('America/Argentina/Salta', 'America/Argentina/Salta'), ('America/Grenada', 'America/Grenada'), ('Asia/Novosibirsk', 'Asia/Novosibirsk'), ('Africa/Ceuta', 'Africa/Ceuta'), ('Australia/West', 'Australia/West'), ('Pacific/Port_Moresby', 'Pacific/Port_Moresby'), ('Pacific/Truk', 'Pacific/Truk'), ('America/Argentina/ComodRivadavia', 'America/Argentina/ComodRivadavia'), ('America/Jamaica', 'America/Jamaica'), ('America/Cordoba', 'America/Cordoba'), ('Pacific/Niue', 'Pacific/Niue'), ('Pacific/Wallis', 'Pacific/Wallis'), ('America/Anchorage', 'America/Anchorage'), ('Asia/Hong_Kong', 'Asia/Hong_Kong'), ('Europe/Rome', 'Europe/Rome'), ('America/Atikokan', 'America/Atikokan'), ('Asia/Jerusalem', 'Asia/Jerusalem'), ('Asia/Krasnoyarsk', 'Asia/Krasnoyarsk'), ('Pacific/Galapagos', 'Pacific/Galapagos'), ('Europe/Moscow', 'Europe/Moscow'), ('Africa/Luanda', 'Africa/Luanda'), ('America/Rio_Branco', 'America/Rio_Branco'), ('Pacific/Fiji', 'Pacific/Fiji'), ('Asia/Khandyga', 'Asia/Khandyga'), ('Indian/Kerguelen', 'Indian/Kerguelen'), ('Africa/Porto-Novo', 'Africa/Porto-Novo'), ('America/North_Dakota/Beulah', 'America/North_Dakota/Beulah'), ('Asia/Shanghai', 'Asia/Shanghai'), ('Europe/Belgrade', 'Europe/Belgrade'), ('Atlantic/Stanley', 'Atlantic/Stanley'), ('Canada/Pacific', 'Canada/Pacific'), ('Asia/Vladivostok', 'Asia/Vladivostok'), ('Africa/Gaborone', 'Africa/Gaborone'), ('Atlantic/Faroe', 'Atlantic/Faroe'), ('Etc/GMT-0', 'Etc/GMT-0'), ('Pacific/Ponape', 'Pacific/Ponape'), ('Australia/Canberra', 'Australia/Canberra'), ('Europe/Warsaw', 'Europe/Warsaw'), ('Etc/GMT-9', 'Etc/GMT-9'), ('America/Iqaluit', 'America/Iqaluit'), ('America/Argentina/Ushuaia', 'America/Argentina/Ushuaia'), ('Europe/Saratov', 'Europe/Saratov'), ('Atlantic/Cape_Verde', 'Atlantic/Cape_Verde'), ('Indian/Maldives', 'Indian/Maldives'), ('Europe/Vilnius', 'Europe/Vilnius'), ('Etc/UCT', 'Etc/UCT'), ('America/Moncton', 'America/Moncton'), ('America/Boa_Vista', 'America/Boa_Vista'), ('US/Central', 'US/Central'), ('America/Halifax', 'America/Halifax'), ('Asia/Phnom_Penh', 'Asia/Phnom_Penh'), ('Africa/Blantyre', 'Africa/Blantyre'), ('Africa/Lome', 'Africa/Lome'), ('Africa/Johannesburg', 'Africa/Johannesburg'), ('Asia/Barnaul', 'Asia/Barnaul'), ('Asia/Amman', 'Asia/Amman'), ('Africa/Malabo', 'Africa/Malabo'), ('America/Mendoza', 'America/Mendoza'), ('Pacific/Tarawa', 'Pacific/Tarawa'), ('Africa/Kinshasa', 'Africa/Kinshasa'), ('Europe/Vienna', 'Europe/Vienna'), ('Australia/Melbourne', 'Australia/Melbourne'), ('America/Argentina/Buenos_Aires', 'America/Argentina/Buenos_Aires'), ('Atlantic/Azores', 'Atlantic/Azores'), ('America/Fort_Wayne', 'America/Fort_Wayne'), ('Africa/Tunis', 'Africa/Tunis'), ('Etc/GMT+2', 'Etc/GMT+2'), ('Asia/Vientiane', 'Asia/Vientiane'), ('Greenwich', 'Greenwich'), ('America/Chihuahua', 'America/Chihuahua'), ('America/Argentina/San_Luis', 'America/Argentina/San_Luis'), ('Asia/Almaty', 'Asia/Almaty'), ('Asia/Kuala_Lumpur', 'Asia/Kuala_Lumpur'), ('America/Puerto_Rico', 'America/Puerto_Rico'), ('Europe/Ljubljana', 'Europe/Ljubljana'), ('Indian/Mahe', 'Indian/Mahe'), ('America/Indiana/Vincennes', 'America/Indiana/Vincennes'), ('Pacific/Guam', 'Pacific/Guam'), ('Asia/Chongqing', 'Asia/Chongqing'), ('America/Catamarca', 'America/Catamarca'), ('Etc/GMT-8', 'Etc/GMT-8'), ('Europe/Copenhagen', 'Europe/Copenhagen'), ('Europe/Prague', 'Europe/Prague'), ('Europe/Zaporozhye', 'Europe/Zaporozhye'), ('Atlantic/St_Helena', 'Atlantic/St_Helena'), ('Australia/NSW', 'Australia/NSW'), ('GB', 'GB'), ('Australia/Yancowinna', 'Australia/Yancowinna'), ('Iran', 'Iran'), ('Atlantic/South_Georgia', 'Atlantic/South_Georgia'), ('Asia/Jakarta', 'Asia/Jakarta'), ('Europe/Mariehamn', 'Europe/Mariehamn'), ('America/Recife', 'America/Recife'), ('America/Ciudad_Juarez', 'America/Ciudad_Juarez'), ('Asia/Tashkent', 'Asia/Tashkent'), ('Kwajalein', 'Kwajalein'), ('America/Bahia_Banderas', 'America/Bahia_Banderas'), ('Etc/GMT', 'Etc/GMT'), ('Africa/Nairobi', 'Africa/Nairobi'), ('Europe/Zurich', 'Europe/Zurich'), ('America/North_Dakota/Center', 'America/North_Dakota/Center'), ('America/Montreal', 'America/Montreal'), ('Asia/Tbilisi', 'Asia/Tbilisi'), ('Asia/Kolkata', 'Asia/Kolkata'), ('America/Mexico_City', 'America/Mexico_City'), ('Indian/Reunion', 'Indian/Reunion'), ('Canada/Central', 'Canada/Central'), ('America/Noronha', 'America/Noronha'), ('Etc/GMT-12', 'Etc/GMT-12'), ('Asia/Bahrain', 'Asia/Bahrain'), ('Japan', 'Japan'), ('Asia/Dubai', 'Asia/Dubai'), ('MET', 'MET'), ('Asia/Tokyo', 'Asia/Tokyo'), ('Europe/Stockholm', 'Europe/Stockholm'), ('Indian/Christmas', 'Indian/Christmas'), ('Navajo', 'Navajo'), ('America/Adak', 'America/Adak'), ('CET', 'CET'), ('America/Belem', 'America/Belem'), ('Europe/Istanbul', 'Europe/Istanbul'), ('Etc/GMT+1', 'Etc/GMT+1'), ('GMT0', 'GMT0'), ('Asia/Manila', 'Asia/Manila'), ('Indian/Cocos', 'Indian/Cocos'), ('PST8PDT', 'PST8PDT'), ('Australia/Darwin', 'Australia/Darwin'), ('Europe/Kiev', 'Europe/Kiev'), ('Poland', 'Poland'), ('Asia/Istanbul', 'Asia/Istanbul'), ('America/Santa_Isabel', 'America/Santa_Isabel'), ('Antarctica/McMurdo', 'Antarctica/McMurdo'), ('Europe/Nicosia', 'Europe/Nicosia'), ('Africa/Timbuktu', 'Africa/Timbuktu'), ('Africa/Juba', 'Africa/Juba'), ('America/Edmonton', 'America/Edmonton'), ('America/Manaus', 'America/Manaus'), ('Etc/GMT-13', 'Etc/GMT-13'), ('Europe/Uzhgorod', 'Europe/Uzhgorod'), ('America/Glace_Bay', 'America/Glace_Bay'), ('Asia/Choibalsan', 'Asia/Choibalsan'), ('US/Arizona', 'US/Arizona'), ('Asia/Irkutsk', 'Asia/Irkutsk'), ('America/Kentucky/Monticello', 'America/Kentucky/Monticello'), ('Etc/GMT-4', 'Etc/GMT-4'), ('America/Virgin', 'America/Virgin'), ('Australia/South', 'Australia/South'), ('Africa/Ndjamena', 'Africa/Ndjamena'), ('Australia/Victoria', 'Australia/Victoria'), ('Africa/Lagos', 'Africa/Lagos'), ('America/Punta_Arenas', 'America/Punta_Arenas'), ('Mexico/BajaNorte', 'Mexico/BajaNorte'), ('MST7MDT', 'MST7MDT'), ('EST', 'EST'), ('Africa/Accra', 'Africa/Accra'), ('America/St_Johns', 'America/St_Johns'), ('Pacific/Chuuk', 'Pacific/Chuuk'), ('Europe/Vaduz', 'Europe/Vaduz'), ('Pacific/Tongatapu', 'Pacific/Tongatapu'), ('America/Jujuy', 'America/Jujuy'), ('America/Shiprock', 'America/Shiprock'), ('Africa/Lusaka', 'Africa/Lusaka'), ('Africa/Sao_Tome', 'Africa/Sao_Tome'), ('America/Vancouver', 'America/Vancouver'), ('Pacific/Guadalcanal', 'Pacific/Guadalcanal'), ('America/Cayenne', 'America/Cayenne'), ('America/Paramaribo', 'America/Paramaribo'), ('America/Dawson_Creek', 'America/Dawson_Creek'), ('ROC', 'ROC'), ('Universal', 'Universal'), ('America/Porto_Acre', 'America/Porto_Acre'), ('Europe/Tirane', 'Europe/Tirane'), ('America/Thule', 'America/Thule'), ('Asia/Ulan_Bator', 'Asia/Ulan_Bator'), ('America/Argentina/La_Rioja', 'America/Argentina/La_Rioja'), ('Etc/GMT+9', 'Etc/GMT+9'), ('Antarctica/Rothera', 'Antarctica/Rothera'), ('Africa/Bamako', 'Africa/Bamako'), ('Africa/Ouagadougou', 'Africa/Ouagadougou'), ('America/Denver', 'America/Denver'), ('Asia/Baku', 'Asia/Baku'), ('Asia/Yakutsk', 'Asia/Yakutsk'), ('Canada/Eastern', 'Canada/Eastern'), ('Pacific/Majuro', 'Pacific/Majuro'), ('Factory', 'Factory'), ('America/Boise', 'America/Boise'), ('Asia/Qatar', 'Asia/Qatar'), ('Canada/Yukon', 'Canada/Yukon'), ('Asia/Srednekolymsk', 'Asia/Srednekolymsk'), ('America/Martinique', 'America/Martinique'), ('US/Michigan', 'US/Michigan'), ('Europe/Andorra', 'Europe/Andorra'), ('Africa/Cairo', 'Africa/Cairo'), ('Europe/Tallinn', 'Europe/Tallinn'), ('Pacific/Fakaofo', 'Pacific/Fakaofo'), ('America/Argentina/Catamarca', 'America/Argentina/Catamarca'), ('Europe/Belfast', 'Europe/Belfast'), ('America/Costa_Rica', 'America/Costa_Rica'), ('Asia/Harbin', 'Asia/Harbin'), ('Europe/Monaco', 'Europe/Monaco'), ('America/Rosario', 'America/Rosario'), ('Europe/Budapest', 'Europe/Budapest'), ('Asia/Dili', 'Asia/Dili'), ('Atlantic/Bermuda', 'Atlantic/Bermuda'), ('Chile/EasterIsland', 'Chile/EasterIsland'), ('Africa/Tripoli', 'Africa/Tripoli'), ('Asia/Kathmandu', 'Asia/Kathmandu'), ('America/Argentina/San_Juan', 'America/Argentina/San_Juan'), ('Asia/Ashkhabad', 'Asia/Ashkhabad'), ('Pacific/Marquesas', 'Pacific/Marquesas'), ('America/Thunder_Bay', 'America/Thunder_Bay'), ('Pacific/Pago_Pago', 'Pacific/Pago_Pago'), ('Brazil/East', 'Brazil/East'), ('US/East-Indiana', 'US/East-Indiana'), ('Pacific/Tahiti', 'Pacific/Tahiti'), ('Eire', 'Eire'), ('Europe/Volgograd', 'Europe/Volgograd'), ('America/Tegucigalpa', 'America/Tegucigalpa'), ('Australia/Queensland', 'Australia/Queensland'), ('America/Eirunepe', 'America/Eirunepe'), ('Etc/GMT-6', 'Etc/GMT-6'), ('Pacific/Norfolk', 'Pacific/Norfolk'), ('Africa/Nouakchott', 'Africa/Nouakchott'), ('America/Yellowknife', 'America/Yellowknife'), ('Europe/Berlin', 'Europe/Berlin'), ('Asia/Brunei', 'Asia/Brunei'), ('Asia/Riyadh', 'Asia/Riyadh'), ('America/Argentina/Tucuman', 'America/Argentina/Tucuman'), ('Asia/Ashgabat', 'Asia/Ashgabat'), ('W-SU', 'W-SU'), ('America/Antigua', 'America/Antigua'), ('America/Nuuk', 'America/Nuuk'), ('America/Chicago', 'America/Chicago'), ('Asia/Karachi', 'Asia/Karachi'), ('Europe/Ulyanovsk', 'Europe/Ulyanovsk'), ('Europe/London', 'Europe/London'), ('Europe/Guernsey', 'Europe/Guernsey'), ('Indian/Mayotte', 'Indian/Mayotte'), ('Asia/Kamchatka', 'Asia/Kamchatka'), ('Australia/Lindeman', 'Australia/Lindeman'), ('America/Los_Angeles', 'America/Los_Angeles'), ('Europe/Jersey', 'Europe/Jersey'), ('Australia/Hobart', 'Australia/Hobart'), ('Asia/Dhaka', 'Asia/Dhaka'), ('Asia/Calcutta', 'Asia/Calcutta'), ('Asia/Singapore', 'Asia/Singapore'), ('America/Coral_Harbour', 'America/Coral_Harbour'), ('US/Alaska', 'US/Alaska'), ('Pacific/Easter', 'Pacific/Easter'), ('Africa/Addis_Ababa', 'Africa/Addis_Ababa'), ('Asia/Chungking', 'Asia/Chungking'), ('Asia/Hovd', 'Asia/Hovd'), ('Etc/GMT+12', 'Etc/GMT+12'), ('Africa/Algiers', 'Africa/Algiers'), ('Asia/Yangon', 'Asia/Yangon'), ('Pacific/Bougainville', 'Pacific/Bougainville'), ('America/Indiana/Petersburg', 'America/Indiana/Petersburg'), ('America/Ojinaga', 'America/Ojinaga'), ('America/Buenos_Aires', 'America/Buenos_Aires'), ('America/Argentina/Rio_Gallegos', 'America/Argentina/Rio_Gallegos'), ('Etc/GMT-7', 'Etc/GMT-7'), ('America/Knox_IN', 'America/Knox_IN'), ('Africa/Asmara', 'Africa/Asmara'), ('Pacific/Enderbury', 'Pacific/Enderbury'), ('Australia/LHI', 'Australia/LHI'), ('Africa/Maputo', 'Africa/Maputo'), ('Africa/Djibouti', 'Africa/Djibouti'), ('America/Sao_Paulo', 'America/Sao_Paulo'), ('America/Cambridge_Bay', 'America/Cambridge_Bay'), ('Pacific/Kwajalein', 'Pacific/Kwajalein'), ('GMT-0', 'GMT-0'), ('America/Tijuana', 'America/Tijuana'), ('Asia/Omsk', 'Asia/Omsk'), ('America/Indiana/Indianapolis', 'America/Indiana/Indianapolis'), ('Etc/Universal', 'Etc/Universal'), ('Asia/Ust-Nera', 'Asia/Ust-Nera'), ('Africa/El_Aaiun', 'Africa/El_Aaiun'), ('America/Cuiaba', 'America/Cuiaba'), ('Pacific/Pitcairn', 'Pacific/Pitcairn'), ('Etc/GMT0', 'Etc/GMT0'), ('Asia/Bangkok', 'Asia/Bangkok'), ('Europe/Lisbon', 'Europe/Lisbon'), ('Asia/Tel_Aviv', 'Asia/Tel_Aviv'), ('America/Lower_Princes', 'America/Lower_Princes'), ('Jamaica', 'Jamaica'), ('America/Santarem', 'America/Santarem'), ('Africa/Brazzaville', 'Africa/Brazzaville'), ('America/Araguaina', 'America/Araguaina'), ('Australia/Brisbane', 'Australia/Brisbane'), ('America/Winnipeg', 'America/Winnipeg'), ('Australia/Adelaide', 'Australia/Adelaide'), ('Canada/Mountain', 'Canada/Mountain'), ('Europe/Paris', 'Europe/Paris'), ('Europe/Samara', 'Europe/Samara'), ('Pacific/Chatham', 'Pacific/Chatham'), ('Indian/Chagos', 'Indian/Chagos'), ('EET', 'EET'), ('Asia/Colombo', 'Asia/Colombo'), ('Antarctica/Vostok', 'Antarctica/Vostok'), ('Mexico/General', 'Mexico/General'), ('Asia/Qostanay', 'Asia/Qostanay'), ('Asia/Urumqi', 'Asia/Urumqi'), ('Europe/Minsk', 'Europe/Minsk'), ('America/Godthab', 'America/Godthab'), ('WET', 'WET'), ('Asia/Novokuznetsk', 'Asia/Novokuznetsk'), ('Europe/Sarajevo', 'Europe/Sarajevo'), ('Europe/Tiraspol', 'Europe/Tiraspol'), ('America/Hermosillo', 'America/Hermosillo'), ('America/St_Thomas', 'America/St_Thomas'), ('Asia/Rangoon', 'Asia/Rangoon'), ('America/Argentina/Jujuy', 'America/Argentina/Jujuy'), ('Etc/GMT+0', 'Etc/GMT+0'), ('Africa/Douala', 'Africa/Douala'), ('Pacific/Noumea', 'Pacific/Noumea'), ('America/Managua', 'America/Managua'), ('America/Santo_Domingo', 'America/Santo_Domingo'), ('NZ', 'NZ'), ('Etc/GMT+3', 'Etc/GMT+3'), ('Turkey', 'Turkey'), ('America/Grand_Turk', 'America/Grand_Turk'), ('America/Whitehorse', 'America/Whitehorse'), ('Asia/Kuwait', 'Asia/Kuwait'), ('Africa/Maseru', 'Africa/Maseru'), ('Europe/Bratislava', 'Europe/Bratislava'), ('Europe/Astrakhan', 'Europe/Astrakhan'), ('America/New_York', 'America/New_York'), ('America/La_Paz', 'America/La_Paz'), ('America/St_Lucia', 'America/St_Lucia'), ('America/Indiana/Knox', 'America/Indiana/Knox'), ('UCT', 'UCT'), ('Etc/GMT+10', 'Etc/GMT+10'), ('Antarctica/Casey', 'Antarctica/Casey'), ('America/Cancun', 'America/Cancun'), ('Europe/Bucharest', 'Europe/Bucharest'), ('America/Regina', 'America/Regina'), ('US/Hawaii', 'US/Hawaii'), ('Antarctica/South_Pole', 'Antarctica/South_Pole'), ('Asia/Magadan', 'Asia/Magadan'), ('Australia/Tasmania', 'Australia/Tasmania'), ('Europe/San_Marino', 'Europe/San_Marino'), ('Atlantic/Canary', 'Atlantic/Canary'), ('Canada/Saskatchewan', 'Canada/Saskatchewan'), ('Asia/Taipei', 'Asia/Taipei'), ('America/Aruba', 'America/Aruba'), ('PRC', 'PRC'), ('America/Rankin_Inlet', 'America/Rankin_Inlet'), ('Etc/GMT+7', 'Etc/GMT+7'), ('Etc/GMT+8', 'Etc/GMT+8'), ('HST', 'HST'), ('Etc/GMT+11', 'Etc/GMT+11'), ('Libya', 'Libya'), ('America/Inuvik', 'America/Inuvik'), ('Asia/Thimbu', 'Asia/Thimbu'), ('Asia/Sakhalin', 'Asia/Sakhalin'), ('Europe/Gibraltar', 'Europe/Gibraltar'), ('Europe/Busingen', 'Europe/Busingen'), ('Asia/Ujung_Pandang', 'Asia/Ujung_Pandang'), ('Etc/GMT-3', 'Etc/GMT-3'), ('America/Juneau', 'America/Juneau'), ('Africa/Freetown', 'Africa/Freetown'), ('Asia/Nicosia', 'Asia/Nicosia'), ('Asia/Yerevan', 'Asia/Yerevan'), ('America/Montserrat', 'America/Montserrat'), ('Pacific/Gambier', 'Pacific/Gambier'), ('America/Campo_Grande', 'America/Campo_Grande'), ('Africa/Mbabane', 'Africa/Mbabane'), ('Europe/Isle_of_Man', 'Europe/Isle_of_Man'), ('Africa/Bangui', 'Africa/Bangui'), ('Asia/Tehran', 'Asia/Tehran'), ('America/Fort_Nelson', 'America/Fort_Nelson'), ('Antarctica/Syowa', 'Antarctica/Syowa'), ('America/Panama', 'America/Panama'), ('Pacific/Yap', 'Pacific/Yap'), ('Chile/Continental', 'Chile/Continental'), ('America/North_Dakota/New_Salem', 'America/North_Dakota/New_Salem'), ('US/Aleutian', 'US/Aleutian'), ('CST6CDT', 'CST6CDT'), ('US/Samoa', 'US/Samoa'), ('America/Indiana/Tell_City', 'America/Indiana/Tell_City'), ('GMT', 'GMT'), ('Asia/Jayapura', 'Asia/Jayapura'), ('Africa/Conakry', 'Africa/Conakry'), ('America/Guatemala', 'America/Guatemala'), ('America/Atka', 'America/Atka'), ('America/Rainy_River', 'America/Rainy_River'), ('Africa/Windhoek', 'Africa/Windhoek'), ('Europe/Kyiv', 'Europe/Kyiv'), ('Asia/Saigon', 'Asia/Saigon'), ('Asia/Makassar', 'Asia/Makassar'), ('Asia/Kabul', 'Asia/Kabul'), ('Europe/Madrid', 'Europe/Madrid'), ('Pacific/Honolulu', 'Pacific/Honolulu'), ('Australia/Sydney', 'Australia/Sydney'), ('Pacific/Rarotonga', 'Pacific/Rarotonga'), ('America/Havana', 'America/Havana'), ('Indian/Comoro', 'Indian/Comoro'), ('America/Kentucky/Louisville', 'America/Kentucky/Louisville'), ('America/Santiago', 'America/Santiago'), ('Etc/GMT+4', 'Etc/GMT+4'), ('Antarctica/Palmer', 'Antarctica/Palmer'), ('Singapore', 'Singapore'), ('Europe/Skopje', 'Europe/Skopje'), ('Pacific/Efate', 'Pacific/Efate'), ('Europe/Helsinki', 'Europe/Helsinki'), ('Antarctica/Troll', 'Antarctica/Troll'), ('America/Asuncion', 'America/Asuncion'), ('Etc/GMT-5', 'Etc/GMT-5'), ('Israel', 'Israel'), ('America/Nassau', 'America/Nassau'), ('Africa/Monrovia', 'Africa/Monrovia'), ('Asia/Qyzylorda', 'Asia/Qyzylorda'), ('America/Cayman', 'America/Cayman'), ('Asia/Oral', 'Asia/Oral'), ('Canada/Newfoundland', 'Canada/Newfoundland'), ('America/St_Vincent', 'America/St_Vincent'), ('America/Monterrey', 'America/Monterrey'), ('Pacific/Kiritimati', 'Pacific/Kiritimati'), ('Asia/Pyongyang', 'Asia/Pyongyang'), ('Asia/Tomsk', 'Asia/Tomsk'), ('America/Blanc-Sablon', 'America/Blanc-Sablon'), ('Pacific/Wake', 'Pacific/Wake'), ('Europe/Podgorica', 'Europe/Podgorica'), ('America/Argentina/Mendoza', 'America/Argentina/Mendoza'), ('America/Port_of_Spain', 'America/Port_of_Spain'), ('Europe/Zagreb', 'Europe/Zagreb'), ('Iceland', 'Iceland'), ('Cuba', 'Cuba'), ('Atlantic/Faeroe', 'Atlantic/Faeroe'), ('America/Indiana/Winamac', 'America/Indiana/Winamac'), ('Asia/Anadyr', 'Asia/Anadyr'), ('Indian/Mauritius', 'Indian/Mauritius'), ('Africa/Dakar', 'Africa/Dakar'), ('MST', 'MST'), ('Arctic/Longyearbyen', 'Arctic/Longyearbyen'), ('Etc/Greenwich', 'Etc/Greenwich'), ('America/Louisville', 'America/Louisville'), ('Brazil/Acre', 'Brazil/Acre'), ('Australia/Currie', 'Australia/Currie'), ('Etc/GMT-14', 'Etc/GMT-14'), ('America/Curacao', 'America/Curacao'), ('America/Resolute', 'America/Resolute'), ('Pacific/Palau', 'Pacific/Palau'), ('Zulu', 'Zulu'), ('America/Nipigon', 'America/Nipigon'), ('Australia/ACT', 'Australia/ACT'), ('Africa/Abidjan', 'Africa/Abidjan'), ('Mexico/BajaSur', 'Mexico/BajaSur'), ('Asia/Beirut', 'Asia/Beirut'), ('US/Indiana-Starke', 'US/Indiana-Starke'), ('Canada/Atlantic', 'Canada/Atlantic'), ('Africa/Asmera', 'Africa/Asmera'), ('Europe/Chisinau', 'Europe/Chisinau'), ('Africa/Libreville', 'Africa/Libreville'), ('Asia/Kashgar', 'Asia/Kashgar'), ('America/Toronto', 'America/Toronto'), ('Asia/Gaza', 'Asia/Gaza'), ('Etc/GMT-10', 'Etc/GMT-10'), ('US/Mountain', 'US/Mountain'), ('ROK', 'ROK'), ('Pacific/Johnston', 'Pacific/Johnston'), ('Europe/Athens', 'Europe/Athens'), ('America/Pangnirtung', 'America/Pangnirtung'), ('Europe/Kaliningrad', 'Europe/Kaliningrad'), ('Asia/Atyrau', 'Asia/Atyrau'), ('Antarctica/Davis', 'Antarctica/Davis'), ('Pacific/Auckland', 'Pacific/Auckland'), ('America/Miquelon', 'America/Miquelon'), ('America/Montevideo', 'America/Montevideo'), ('Asia/Macau', 'Asia/Macau'), ('America/Kralendijk', 'America/Kralendijk'), ('Asia/Samarkand', 'Asia/Samarkand'), ('America/Phoenix', 'America/Phoenix'), ('America/Merida', 'America/Merida'), ('America/St_Kitts', 'America/St_Kitts'), ('Pacific/Saipan', 'Pacific/Saipan'), ('America/Guadeloupe', 'America/Guadeloupe'), ('US/Pacific', 'US/Pacific'), ('America/Marigot', 'America/Marigot'), ('Etc/GMT+6', 'Etc/GMT+6'), ('Africa/Harare', 'Africa/Harare'), ('Africa/Bissau', 'Africa/Bissau'), ('NZ-CHAT', 'NZ-CHAT'), ('Asia/Aden', 'Asia/Aden'), ('America/Port-au-Prince', 'America/Port-au-Prince'), ('Hongkong', 'Hongkong'), ('Europe/Riga', 'Europe/Riga'), ('Asia/Bishkek', 'Asia/Bishkek'), ('America/El_Salvador', 'America/El_Salvador'), ('Pacific/Midway', 'Pacific/Midway'), ('America/Ensenada', 'America/Ensenada'), ('Egypt', 'Egypt'), ('Africa/Casablanca', 'Africa/Casablanca'), ('Europe/Simferopol', 'Europe/Simferopol'), ('America/Bahia', 'America/Bahia'), ('Australia/Broken_Hill', 'Australia/Broken_Hill'), ('Portugal', 'Portugal'), ('America/Guayaquil', 'America/Guayaquil'), ('America/Dominica', 'America/Dominica'), ('America/Nome', 'America/Nome'), ('America/Argentina/Cordoba', 'America/Argentina/Cordoba'), ('America/Lima', 'America/Lima'), ('America/Porto_Velho', 'America/Porto_Velho'), ('Asia/Aqtau', 'Asia/Aqtau'), ('Pacific/Pohnpei', 'Pacific/Pohnpei'), ('Australia/Eucla', 'Australia/Eucla'), ('Etc/GMT-2', 'Etc/GMT-2'), ('Asia/Aqtobe', 'Asia/Aqtobe'), ('Asia/Hebron', 'Asia/Hebron'), ('Australia/North', 'Australia/North'), ('America/Detroit', 'America/Detroit'), ('Asia/Pontianak', 'Asia/Pontianak'), ('America/Bogota', 'America/Bogota'), ('Pacific/Kosrae', 'Pacific/Kosrae'), ('Europe/Dublin', 'Europe/Dublin'), ('America/Matamoros', 'America/Matamoros'), ('US/Eastern', 'US/Eastern'), ('Asia/Katmandu', 'Asia/Katmandu'), ('Antarctica/Mawson', 'Antarctica/Mawson'), ('Asia/Baghdad', 'Asia/Baghdad'), ('Pacific/Funafuti', 'Pacific/Funafuti'), ('Europe/Amsterdam', 'Europe/Amsterdam'), ('America/Barbados', 'America/Barbados'), ('Europe/Malta', 'Europe/Malta'), ('America/Dawson', 'America/Dawson'), ('Africa/Khartoum', 'Africa/Khartoum'), ('Etc/Zulu', 'Etc/Zulu'), ('America/Belize', 'America/Belize'), ('Asia/Thimphu', 'Asia/Thimphu'), ('Africa/Lubumbashi', 'Africa/Lubumbashi'), ('America/Caracas', 'America/Caracas'), ('Pacific/Apia', 'Pacific/Apia'), ('America/Fortaleza', 'America/Fortaleza'), ('Atlantic/Madeira', 'Atlantic/Madeira'), ('Asia/Kuching', 'Asia/Kuching'), ('Europe/Sofia', 'Europe/Sofia'), ('America/Tortola', 'America/Tortola'), ('Asia/Ho_Chi_Minh', 'Asia/Ho_Chi_Minh'), ('America/St_Barthelemy', 'America/St_Barthelemy'), ('America/Metlakatla', 'America/Metlakatla'), ('Antarctica/Macquarie', 'Antarctica/Macquarie'), ('Africa/Kampala', 'Africa/Kampala'), ('Africa/Bujumbura', 'Africa/Bujumbura'), ('Europe/Vatican', 'Europe/Vatican'), ('Atlantic/Jan_Mayen', 'Atlantic/Jan_Mayen'), ('Asia/Famagusta', 'Asia/Famagusta'), ('Australia/Lord_Howe', 'Australia/Lord_Howe'), ('America/Sitka', 'America/Sitka'), ('America/Indiana/Vevay', 'America/Indiana/Vevay'), ('Etc/GMT+5', 'Etc/GMT+5'), ('America/Indianapolis', 'America/Indianapolis'), ('Asia/Ulaanbaatar', 'Asia/Ulaanbaatar')], default='Asia/Kolkata', max_length=50, verbose_name='Time zone'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='version',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='worldsettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
