# Generated by Django 4.2.6 on 2023-10-17 15:32

import creme.creme_core.core.utils
import creme.creme_core.models.fields.autoslugfield
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_billingaddress_country_communicationevent_event_type_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankcard',
            options={'verbose_name': 'Thẻ ngân hàng', 'verbose_name_plural': 'Các loại thẻ ngân hàng'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['pk'], 'verbose_name': 'Nguồn', 'verbose_name_plural': 'Các nguồn'},
        ),
        migrations.AlterModelOptions(
            name='sourcetype',
            options={'ordering': ['name'], 'verbose_name': 'Loại nguồn', 'verbose_name_plural': 'Các loại nguồn'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_created'], 'verbose_name': 'Giao dịch', 'verbose_name_plural': 'Các giao dịch'},
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='card_type',
            field=models.CharField(max_length=128, verbose_name='Loại thẻ'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='expiry_date',
            field=models.DateField(verbose_name='Ngày hết hạn'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='number',
            field=models.CharField(max_length=32, verbose_name='Số'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='partner_reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tài liều đối tác'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankcards', to=settings.AUTH_USER_MODEL, verbose_name='Tên khách hàng'),
        ),
        migrations.AlterField(
            model_name='source',
            name='amount_allocated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Số tiền phân bổ'),
        ),
        migrations.AlterField(
            model_name='source',
            name='amount_debited',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Số tiền nợ'),
        ),
        migrations.AlterField(
            model_name='source',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Số tiền hoàn trả'),
        ),
        migrations.AlterField(
            model_name='source',
            name='currency',
            field=models.CharField(default=creme.creme_core.core.utils.get_default_currency, max_length=12, verbose_name='Tiền tệ'),
        ),
        migrations.AlterField(
            model_name='source',
            name='label',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nhãn'),
        ),
        migrations.AlterField(
            model_name='source',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='order.order', verbose_name='Đơn hàng '),
        ),
        migrations.AlterField(
            model_name='source',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='tài liêu tham khảo'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='payment.sourcetype', verbose_name='Loại nguồn'),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='code',
            field=creme.creme_core.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, help_text='Điều này được sử dụng trong các hình thức để xác định nguồn loại này', max_length=128, populate_from='name', unique=True, verbose_name='Mã '),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Ngày tạo '),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=128, verbose_name='tài liêu tham khảo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.source', verbose_name='Nguồn'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, max_length=128, verbose_name='Trạng thái '),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(blank=True, max_length=128, verbose_name='Kiểu '),
        ),
    ]
