# Generated by Django 4.2.6 on 2023-10-17 15:32

import creme.creme_core.core.utils
import creme.creme_core.models.fields.slugfield
from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0002_alter_attributeoption_options_and_more'),
        ('basket', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Giỏ hàng', 'verbose_name_plural': 'Những giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['date_created', 'pk'], 'verbose_name': 'Giỏ hàng dây ', 'verbose_name_plural': 'Những giỏ hàng '},
        ),
        migrations.AlterModelOptions(
            name='lineattribute',
            options={'verbose_name': 'Thuộc tính dây ', 'verbose_name_plural': 'Những thuộc tính dây '},
        ),
        migrations.AlterField(
            model_name='basket',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='date_merged',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày sửa'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày gửi'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL, verbose_name='Chủ sở hữu'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('Open', 'Hiện đang hoạt '), ('Merged', 'Sáp nhập- Trộn tất cả các giỏ hàng'), ('Saved', 'Lưu những món hàng để mua '), ('Frozen', 'Khóa lại - Giỏ hàng không thể thay đổi'), ('Submitted', 'Gửi đơn hàng khi thanh toán.')], default='Open', max_length=128, verbose_name='Trạng thái '),
        ),
        migrations.AlterField(
            model_name='basket',
            name='vouchers',
            field=models.ManyToManyField(blank=True, to='voucher.voucher', verbose_name='Phiếu giảm giá'),
        ),
        migrations.AlterField(
            model_name='line',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='basket.basket', verbose_name='Giỏ hàng'),
        ),
        migrations.AlterField(
            model_name='line',
            name='date_created',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Ngày tạo '),
        ),
        migrations.AlterField(
            model_name='line',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Ngày cập nhật '),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_reference',
            field=creme.creme_core.models.fields.slugfield.SlugField(max_length=128, verbose_name='Tham khảo'),
        ),
        migrations.AlterField(
            model_name='line',
            name='price_currency',
            field=models.CharField(default=creme.creme_core.core.utils.get_default_currency, max_length=12, verbose_name='Tiền tệ'),
        ),
        migrations.AlterField(
            model_name='line',
            name='price_excl_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Giá chưa bao gồm thuế'),
        ),
        migrations.AlterField(
            model_name='line',
            name='price_incl_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Giá bao gồm thuế'),
        ),
        migrations.AlterField(
            model_name='line',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_lines', to='catalogue.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='line',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='lineattribute',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='basket.line', verbose_name='dây '),
        ),
        migrations.AlterField(
            model_name='lineattribute',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.option', verbose_name='Lựa chọn '),
        ),
        migrations.AlterField(
            model_name='lineattribute',
            name='value',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Giá trị '),
        ),
    ]
