# Generated by Django 4.2.6 on 2023-10-13 14:33

import creme.creme_core.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("creme_core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="Action")),
                ("source", models.CharField(max_length=100, verbose_name="Source")),
                ("raw_data", models.BinaryField(blank=True, null=True)),
                ("subject", models.CharField(max_length=100, verbose_name="Subject")),
                (
                    "ct",
                    creme.creme_core.models.fields.CTypeForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Type of resource",
                    ),
                ),
                (
                    "user",
                    creme.creme_core.models.fields.CremeUserForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waiting action",
                "verbose_name_plural": "Waiting actions",
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    creme.creme_core.models.fields.CreationDateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Creation date",
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="Action")),
                ("source", models.CharField(max_length=100, verbose_name="Source")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creme_core.cremeentity",
                        verbose_name="Entity",
                    ),
                ),
                (
                    "user",
                    creme.creme_core.models.fields.CremeUserForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "History",
                "verbose_name_plural": "History",
            },
        ),
    ]
