# Generated by Django 4.2.6 on 2023-10-17 15:32

import creme.creme_core.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crudity', '0002_alter_history_id_alter_waitingaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingaction',
            name='action',
            field=models.CharField(max_length=100, verbose_name='Hành động'),
        ),
        migrations.AlterField(
            model_name='waitingaction',
            name='source',
            field=models.CharField(max_length=100, verbose_name='Nguồn'),
        ),
        migrations.AlterField(
            model_name='waitingaction',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Chủ đề '),
        ),
        migrations.AlterField(
            model_name='waitingaction',
            name='user',
            field=creme.creme_core.models.fields.CremeUserForeignKey(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Chủ sở hữu'),
        ),
    ]
