# Generated by Django 4.2.6 on 2023-10-13 14:33

import creme.creme_core.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creme_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Act",
            fields=[
                (
                    "cremeentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="creme_core.cremeentity",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Name of the commercial action"
                    ),
                ),
                (
                    "expected_sales",
                    models.PositiveIntegerField(verbose_name="Expected sales"),
                ),
                (
                    "cost",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Cost of the commercial action",
                    ),
                ),
                (
                    "goal",
                    models.TextField(blank=True, verbose_name="Goal of the action"),
                ),
                ("start", models.DateField(verbose_name="Start")),
                ("due_date", models.DateField(verbose_name="Due date")),
            ],
            options={
                "verbose_name": "Commercial action",
                "verbose_name_plural": "Commercial actions",
                "ordering": ("name",),
                "abstract": False,
                "swappable": "COMMERCIAL_ACT_MODEL",
            },
            bases=("creme_core.cremeentity",),
        ),
        migrations.CreateModel(
            name="ActObjectivePattern",
            fields=[
                (
                    "cremeentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="creme_core.cremeentity",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "average_sales",
                    models.PositiveIntegerField(verbose_name="Average sales"),
                ),
            ],
            options={
                "verbose_name": "Objective pattern",
                "verbose_name_plural": "Objective patterns",
                "ordering": ("name",),
                "abstract": False,
                "swappable": "COMMERCIAL_PATTERN_MODEL",
            },
            bases=("creme_core.cremeentity",),
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "cremeentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="creme_core.cremeentity",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Commercial strategy",
                "verbose_name_plural": "Commercial strategies",
                "ordering": ("name",),
                "abstract": False,
                "swappable": "COMMERCIAL_STRATEGY_MODEL",
            },
            bases=("creme_core.cremeentity",),
        ),
        migrations.CreateModel(
            name="ActObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "counter",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Counter"
                    ),
                ),
                (
                    "counter_goal",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Value to reach"
                    ),
                ),
            ],
            options={
                "verbose_name": "Commercial Objective",
                "verbose_name_plural": "Commercial Objectives",
            },
        ),
        migrations.CreateModel(
            name="ActObjectivePatternComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "success_rate",
                    models.PositiveIntegerField(verbose_name="Success rate"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_custom", models.BooleanField(default=True)),
                ("extra_data", models.JSONField(default=dict, editable=False)),
                ("title", models.CharField(max_length=75, verbose_name="Title")),
            ],
            options={
                "verbose_name": "Type of commercial action",
                "verbose_name_plural": "Types of commercial actions",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="CommercialApproach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "creation_date",
                    creme.creme_core.models.fields.CreationDateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Creation date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commercial approach",
                "verbose_name_plural": "Commercial approaches",
            },
        ),
        migrations.CreateModel(
            name="CommercialAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Commercial asset",
                "verbose_name_plural": "Commercial assets",
            },
        ),
        migrations.CreateModel(
            name="CommercialAssetScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MarketSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Market segment",
                "verbose_name_plural": "Market segments",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="MarketSegmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MarketSegmentCharm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Segment charm",
                "verbose_name_plural": "Segment charms",
            },
        ),
        migrations.CreateModel(
            name="MarketSegmentDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.TextField(blank=True, verbose_name="Product")),
                ("place", models.TextField(blank=True, verbose_name="Place")),
                ("price", models.TextField(blank=True, verbose_name="Price")),
                ("promotion", models.TextField(blank=True, verbose_name="Promotion")),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commercial.marketsegment",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segment_info",
                        to=settings.COMMERCIAL_STRATEGY_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Market segment description",
                "verbose_name_plural": "Market segment descriptions",
            },
        ),
        migrations.CreateModel(
            name="MarketSegmentCharmScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
                (
                    "charm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commercial.marketsegmentcharm",
                    ),
                ),
            ],
        ),
    ]
