# Generated by Django 4.2.6 on 2023-10-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_customnotification_id_alter_friend_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='message',
            field=models.TextField(blank=True, verbose_name='Tin nhắn'),
        ),
    ]
