# Generated by Django 4.2.6 on 2023-10-13 14:33

import creme.creme_core.models.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "is_ok",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="Expected reaction has been done",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Source action"),
                ),
                (
                    "creation_date",
                    creme.creme_core.models.fields.CreationDateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Creation date",
                    ),
                ),
                (
                    "expected_reaction",
                    models.TextField(blank=True, verbose_name="Target action"),
                ),
                ("deadline", models.DateTimeField(verbose_name="Deadline")),
                (
                    "validation_date",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Validation date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action",
                "verbose_name_plural": "Actions",
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Validated"
                    ),
                ),
                (
                    "trigger_date",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="Trigger date"
                    ),
                ),
                ("trigger_offset", models.JSONField(default=dict, editable=False)),
                (
                    "reminded",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Notification sent"
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
            },
        ),
        migrations.CreateModel(
            name="Memo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "on_homepage",
                    models.BooleanField(
                        default=False, verbose_name="Displayed on homepage"
                    ),
                ),
                (
                    "creation_date",
                    creme.creme_core.models.fields.CreationDateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Creation date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Memo",
                "verbose_name_plural": "Memos",
            },
        ),
        migrations.CreateModel(
            name="ToDo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "is_ok",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Done?"
                    ),
                ),
                (
                    "reminded",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Notification sent"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "creation_date",
                    creme.creme_core.models.fields.CreationDateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Creation date",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deadline"
                    ),
                ),
            ],
            options={
                "verbose_name": "Todo",
                "verbose_name_plural": "Todos",
            },
        ),
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("body", models.TextField(verbose_name="Message body")),
                ("creation_date", models.DateTimeField(verbose_name="Creation date")),
                ("email_sent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "User message",
                "verbose_name_plural": "User messages",
            },
        ),
        migrations.CreateModel(
            name="UserMessagePriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_custom", models.BooleanField(default=True)),
                ("extra_data", models.JSONField(default=dict, editable=False)),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
            ],
            options={
                "verbose_name": "Priority of user message",
                "verbose_name_plural": "Priorities of user message",
                "ordering": ("title",),
            },
        ),
    ]
