# Generated by Django 4.2.6 on 2023-10-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_alter_conference_id_alter_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc '),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu '),
        ),
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='section',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc '),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(verbose_name='Tiêu đề '),
        ),
        migrations.AlterField(
            model_name='section',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu '),
        ),
    ]
