# Generated by Django 4.2.6 on 2023-10-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='content_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('listing_text_vi', 'Listing Text (Tiếng Việt)'), ('listing_text_en', 'Listing Text (English)'), ('listing_text_fr', 'Listing Text (Français)'), ('listing_text_ja', 'Listing Text (Japanese)'), ('listing_text_ko', 'Listing Text (Korean)'), ('listing_text_de', 'Listing Text (German)'), ('listing_text_ru', 'Listing Text (Russian)')], default='simple', max_length=20, verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='benefitlevel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sponsorbenefit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sponsorlevel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
