# Generated by Django 4.2.6 on 2023-10-17 15:32

from ...creme_core.core import validators
import creme.creme_core.models.fields
import creme.creme_core.models.fields.autoslugfield
import creme.creme_core.models.fields.slugfield
import creme.creme_core.utils.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributeoption',
            options={'verbose_name': 'Thuộc tính lựa chọn ', 'verbose_name_plural': 'Lựa chọn thuộc tính '},
        ),
        migrations.AlterModelOptions(
            name='attributeoptiongroup',
            options={'verbose_name': 'Thuộc tính nhóm sản phẩm ', 'verbose_name_plural': 'Những giá trị nhóm sản phẩm '},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['path'], 'verbose_name': 'Danh mục ', 'verbose_name_plural': 'Phân loại'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Lựa chọn ', 'verbose_name_plural': 'Lựa chọn '},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_created'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ['code'], 'verbose_name': 'Thuộc tính sản phẩm ', 'verbose_name_plural': 'Những thuộc tính sản phẩm '},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'Giá trị thuộc tính sản phẩm ', 'verbose_name_plural': 'Những giá trị thuộc tính sản phẩm '},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['product', 'category'], 'verbose_name': 'Danh mục hàng hóa ', 'verbose_name_plural': 'Những danh mục hàng hóa '},
        ),
        migrations.AlterModelOptions(
            name='productclass',
            options={'ordering': ['name'], 'verbose_name': 'Dòng sản phẩm ', 'verbose_name_plural': 'Những dòng sản phẩm '},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['display_order'], 'verbose_name': 'Hình ảnh sản phẩm ', 'verbose_name_plural': 'Những hình ảnh của sản phẩm '},
        ),
        migrations.AlterModelOptions(
            name='productrecommendation',
            options={'ordering': ['primary', '-ranking'], 'verbose_name': 'Sản phẩm đề nghị ', 'verbose_name_plural': 'Những sản phẩm đề nghị '},
        ),
        migrations.AlterField(
            model_name='attributeoption',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalogue.attributeoptiongroup', verbose_name='Nhóm '),
        ),
        migrations.AlterField(
            model_name='attributeoption',
            name='option',
            field=models.CharField(max_length=255, verbose_name='Lựa chọn '),
        ),
        migrations.AlterField(
            model_name='attributeoptiongroup',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả chi tiết '),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='categories', verbose_name='Hình ảnh '),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Show this category in search results and catalogue listings.', verbose_name='Là công khai'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=creme.creme_core.models.fields.slugfield.SlugField(max_length=255, verbose_name='Tiêu đề '),
        ),
        migrations.AlterField(
            model_name='option',
            name='code',
            field=creme.creme_core.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=128, populate_from='name', unique=True, verbose_name='Mã '),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_group',
            field=models.ForeignKey(blank=True, help_text='Select an option group if using type "Option" or "Multi Option"', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='catalogue.attributeoptiongroup', verbose_name='Lựa chọn nhóm '),
        ),
        migrations.AlterField(
            model_name='option',
            name='order',
            field=models.IntegerField(blank=True, db_index=True, help_text='Controls the ordering of product options on product detail pages', null=True, verbose_name='Sắp xếp'),
        ),
        migrations.AlterField(
            model_name='option',
            name='type',
            field=models.CharField(choices=[('text', 'Chữ '), ('integer', 'Số '), ('boolean', 'Đúng / Sai '), ('float', 'Số nguyên '), ('date', 'Ngày '), ('select', 'Select'), ('radio', 'Radio'), ('multi_select', 'Multi select'), ('checkbox', 'Checkbox')], default='text', max_length=255, verbose_name='Kiểu '),
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(help_text='Một thuộc tính của sản phẩm là điều mà sản phẩm này có thể có, chẳng hạn như kích thước, màu sắc...', through='catalogue.ProductAttributeValue', to='catalogue.productattribute', verbose_name='Thuộc tính '),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(through='catalogue.ProductCategory', to='catalogue.category', verbose_name='Phân loại'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Ngày cập nhật '),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả chi tiết '),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_discountable',
            field=models.BooleanField(default=True, help_text='Đánh dấu  này cho biết sản phẩm này có thể được sử dụng trong một đề xuất hay không ? ', verbose_name='Là sản phẩm giảm giá ? '),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Hiện sản phẩm này trong kết quả tìm kiếm và catalog', verbose_name='Là công khai'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Chỉ chọn một sản phẩm làm  gốc nếu bạn đang tạo ra một sản phẩm nhỏ hơn . Ví dụ, nếu đây là một kích thước 4 của một t-shirt đặc biệt. Để trống nếu điều này là một sản phẩm độc lập (tức là chỉ có một phiên bản của sản phẩm này).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogue.product', verbose_name='Sản phẩm trước '),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_class',
            field=models.ForeignKey(blank=True, help_text='Chọn loại sản phẩm này là', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogue.productclass', verbose_name='Kiểu sản phẩm '),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_options',
            field=models.ManyToManyField(blank=True, help_text='Tùy chọn là giá trị mà có thể được liên kết với một mục khi nó được thêm vào giỏ của khách hàng. Đây có thể là một cái gì đó giống như một tin nhắn cá nhân để được in trên một T-shirt.', to='catalogue.option', verbose_name='Lựa chọn sản phẩm '),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(editable=False, null=True, verbose_name='Xếp hạng '),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, help_text='Đây là những sản phẩm được đề nghị để đi cùng với các sản phẩm chính.', through='catalogue.ProductRecommendation', to='catalogue.product', verbose_name='Sản phẩm đề xuất '),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=creme.creme_core.models.fields.slugfield.SlugField(max_length=255, verbose_name='Tiêu đề '),
        ),
        migrations.AlterField(
            model_name='product',
            name='structure',
            field=models.CharField(choices=[('standalone', 'Sản phẩm riêng lẻ '), ('parent', 'Sản phẩm trước '), ('child', 'Sản phẩm sau ')], default='standalone', max_length=10, verbose_name='Cấu trúc sản phẩm '),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=creme.creme_core.models.fields.NullCharField(help_text='Mã vạch sản phẩm (UPC) là một định danh cho một sản phẩm mà không phải là cụ thể cho một nhà cung cấp cụ thể. Ví dụ: mã vạch cho một cuốn sách. ', max_length=64, unique=True, verbose_name='UPC'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='code',
            field=models.SlugField(max_length=128, validators=[django.core.validators.RegexValidator(message='Mã chỉ có thể bao gồm các ký tự  a-z, A-Z, số , gạch dưới, và không thể bắt đầu với số.', regex='^[a-zA-Z_][0-9a-zA-Z_]*$'), creme.creme_core.core.validators.non_python_keyword], verbose_name='Mã '),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='option_group',
            field=models.ForeignKey(blank=True, help_text='Select an option group if using type "Option" or "Multi Option"', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='catalogue.attributeoptiongroup', verbose_name='Lựa chọn nhóm '),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalogue.productclass', verbose_name='Kiểu sản phẩm '),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Yêu cầu '),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='type',
            field=models.CharField(choices=[('text', 'Chữ '), ('integer', 'Số '), ('boolean', 'Đúng / Sai '), ('float', 'Số nguyên '), ('richtext', 'Nhiều chữ '), ('date', 'Ngày '), ('datetime', 'Ngày-giờ'), ('option', 'Lựa chọn '), ('multi_option', 'Multi Option'), ('entity', 'Chủ thể '), ('file', 'Thư mục '), ('image', 'Hình ảnh ')], default='text', max_length=20, verbose_name='Kiểu '),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.productattribute', verbose_name='Thuộc tính '),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalogue.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_boolean',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Đúng / Sai '),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Ngày '),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_float',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Số nguyên '),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_integer',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Số '),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.attributeoption', verbose_name='Giá trị lựa chọn '),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_richtext',
            field=models.TextField(blank=True, null=True, verbose_name='Văn bản '),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_text',
            field=models.TextField(blank=True, null=True, verbose_name='Chữ '),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.category', verbose_name='Danh mục '),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='options',
            field=models.ManyToManyField(blank=True, to='catalogue.option', verbose_name='Lựa chọn '),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='requires_shipping',
            field=models.BooleanField(default=True, verbose_name='Yêu cầu giao hàng ? '),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='slug',
            field=creme.creme_core.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=128, populate_from='name', unique=True, verbose_name='Tiêu đề '),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='track_stock',
            field=models.BooleanField(default=True, verbose_name='Kiểm tra mức độ tồn kho ?'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chú thích '),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Hình ảnh với số thứ tự hiển thị bằng 0 sẽ là hình ảnh chính cho sản phẩm', verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='original',
            field=models.ImageField(max_length=255, upload_to=creme.creme_core.utils.models.get_image_upload_path, verbose_name='Nguồn gốc '),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='primary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_recommendations', to='catalogue.product', verbose_name='Sản phẩm chính '),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='ranking',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Xác định thứ tự của các sản phẩm. Một sản phẩm có giá trị cao hơn sẽ xuất hiện trước khi một người với một thứ hạng thấp hơn.', verbose_name='Xếp hạng '),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product', verbose_name='Sản phẩm đề nghị '),
        ),
    ]
