# Generated by Django 4.2.6 on 2023-10-13 14:33

import creme.creme_core.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creme_core", "0005_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "cremeentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="creme_core.cremeentity",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of the report"),
                ),
                (
                    "ct",
                    creme.creme_core.models.fields.EntityCTypeForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Entity type",
                    ),
                ),
                (
                    "filter",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"filter_type": 1},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="creme_core.entityfilter",
                        verbose_name="Filter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ("name",),
                "abstract": False,
                "swappable": "REPORTS_REPORT_MODEL",
            },
            bases=("creme_core.cremeentity",),
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField()),
                ("selected", models.BooleanField(default=False)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to=settings.REPORTS_REPORT_MODEL,
                    ),
                ),
                (
                    "sub_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.REPORTS_REPORT_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Column of report",
                "verbose_name_plural": "Columns of report",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="ReportGraph",
            fields=[
                (
                    "cremeentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="creme_core.cremeentity",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of the graph"),
                ),
                (
                    "abscissa_type",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "By days"),
                            (2, "By months"),
                            (3, "By years"),
                            (4, "By X days"),
                            (5, "By values"),
                            (6, "By values (of related entities)"),
                            (11, "By days (custom field)"),
                            (12, "By months (custom field)"),
                            (13, "By years (custom field)"),
                            (14, "By X days (custom field)"),
                            (15, "By values (of custom choices)"),
                        ],
                        editable=False,
                        verbose_name="X axis (grouping)",
                    ),
                ),
                (
                    "abscissa_cell_value",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="X axis (field)"
                    ),
                ),
                (
                    "abscissa_parameter",
                    models.TextField(
                        editable=False, null=True, verbose_name="X axis parameter"
                    ),
                ),
                (
                    "ordinate_type",
                    models.CharField(
                        choices=[
                            ("count", "Count"),
                            ("avg", "Average"),
                            ("max", "Maximum"),
                            ("min", "Minimum"),
                            ("sum", "Sum"),
                        ],
                        default="",
                        editable=False,
                        max_length=100,
                        verbose_name="Y axis (type)",
                    ),
                ),
                (
                    "ordinate_cell_key",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=100,
                        verbose_name="Y axis (field)",
                    ),
                ),
                (
                    "chart",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Chart type"
                    ),
                ),
                (
                    "asc",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="ASC order"
                    ),
                ),
                (
                    "linked_report",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.REPORTS_REPORT_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report's graph",
                "verbose_name_plural": "Reports' graphs",
                "ordering": ["name"],
                "abstract": False,
                "swappable": "REPORTS_GRAPH_MODEL",
            },
            bases=("creme_core.cremeentity",),
        ),
    ]
