# Generated by Django 4.2.6 on 2023-10-17 18:21

import creme.documents.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_folder_options_alter_document_categories_and_more"),
        ("products", "0002_alter_category_id_alter_subcategory_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name",),
                "verbose_name": "Sản phẩm",
                "verbose_name_plural": "Sản phẩm",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Mô tả chi tiết "
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="products.category",
                verbose_name="Danh mục ",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.IntegerField(default=0, verbose_name="Mã "),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=creme.documents.models.fields.ImageEntityManyToManyField(
                blank=True, to="documents.document", verbose_name="Hình ảnh"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Tên"),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="description",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Mô tả chi tiết "
            ),
        ),
    ]
