# Generated by Django 4.2.6 on 2023-10-13 14:33

import creme.creme_core.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0001_initial"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="teams",
            field=models.ManyToManyField(
                related_name="document_teams", to="teams.teams"
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent's category will be copied if you do not select one.",
                null=True,
                on_delete=creme.creme_core.models.deletion.CREME_REPLACE_NULL,
                related_name="folder_category_set",
                to="documents.foldercategory",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="modified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.DOCUMENTS_FOLDER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="parent_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to=settings.DOCUMENTS_FOLDER_MODEL,
                verbose_name="Parent folder",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="foldershareduser",
            unique_together={("folder", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="documentshareduser",
            unique_together={("document", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together={("title", "parent_folder", "category")},
        ),
    ]
