# Generated by Django 4.2.6 on 2023-10-17 15:32

import creme.creme_core.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentcategory_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ('title',), 'verbose_name': 'Thư mục', 'verbose_name_plural': 'Những thư mục'},
        ),
        migrations.AlterField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(blank=True, to='documents.documentcategory', verbose_name='Phân loại'),
        ),
        migrations.AlterField(
            model_name='document',
            name='filedata',
            field=models.FileField(max_length=500, upload_to='documents', verbose_name='Thư mục '),
        ),
        migrations.AlterField(
            model_name='document',
            name='linked_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folder_document', to=settings.DOCUMENTS_FOLDER_MODEL, verbose_name='Thư mục'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='category',
            field=models.ForeignKey(blank=True, help_text="The parent's category will be copied if you do not select one.", null=True, on_delete=creme.creme_core.models.deletion.CREME_REPLACE_NULL, related_name='folder_category_set', to='documents.foldercategory', verbose_name='Danh mục '),
        ),
        migrations.AlterField(
            model_name='folder',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tiêu đề'),
        ),
    ]
