# Generated by Django 4.2.6 on 2023-10-13 14:33

import creme.creme_core.models.deletion
import creme.creme_core.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creme_core", "0005_initial"),
        migrations.swappable_dependency(settings.PERSONS_CONTACT_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "cremeentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="creme_core.cremeentity",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Name of the project"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Estimated start"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Estimated end"
                    ),
                ),
                (
                    "effective_end_date",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Effective end date",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="creme_core.currency",
                        verbose_name="Currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ("name",),
                "abstract": False,
                "swappable": "PROJECTS_PROJECT_MODEL",
            },
            bases=("creme_core.cremeentity",),
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "cremeentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="creme_core.cremeentity",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "order",
                    models.PositiveIntegerField(editable=False, verbose_name="Order"),
                ),
                ("start", models.DateTimeField(verbose_name="Start")),
                ("end", models.DateTimeField(verbose_name="End")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Duration (in hours)"
                    ),
                ),
                (
                    "linked_project",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_set",
                        to=settings.PROJECTS_PROJECT_MODEL,
                        verbose_name="Project",
                    ),
                ),
                (
                    "parent_tasks",
                    models.ManyToManyField(
                        editable=False,
                        related_name="children",
                        to=settings.PROJECTS_TASK_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task of project",
                "verbose_name_plural": "Tasks of project",
                "ordering": ("-start",),
                "abstract": False,
                "swappable": "PROJECTS_TASK_MODEL",
            },
            bases=("creme_core.cremeentity",),
        ),
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_custom", models.BooleanField(default=True)),
                ("extra_data", models.JSONField(default=dict, editable=False)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "color_code",
                    creme.creme_core.models.fields.ColorField(
                        blank=True, max_length=6, verbose_name="Color"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "order",
                    creme.creme_core.models.fields.BasicAutoField(
                        blank=True, editable=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Status of project",
                "verbose_name_plural": "Status of project",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_custom", models.BooleanField(default=True)),
                ("extra_data", models.JSONField(default=dict, editable=False)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "color_code",
                    creme.creme_core.models.fields.ColorField(
                        blank=True, max_length=6, verbose_name="Color"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "order",
                    creme.creme_core.models.fields.BasicAutoField(
                        blank=True, editable=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Status of task",
                "verbose_name_plural": "Status of task",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hourly_cost",
                    models.PositiveIntegerField(default=0, verbose_name="Hourly cost"),
                ),
                (
                    "linked_contact",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.PERSONS_CONTACT_MODEL,
                        verbose_name="Contact",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources_set",
                        to=settings.PROJECTS_TASK_MODEL,
                        verbose_name="Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource of project",
                "verbose_name_plural": "Resources of project",
            },
        ),
        migrations.AddField(
            model_name="projecttask",
            name="tstatus",
            field=models.ForeignKey(
                on_delete=creme.creme_core.models.deletion.CREME_REPLACE,
                to="projects.taskstatus",
                verbose_name="Task situation",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.ForeignKey(
                on_delete=creme.creme_core.models.deletion.CREME_REPLACE,
                to="projects.projectstatus",
                verbose_name="Status",
            ),
        ),
    ]
