# Generated by Django 4.2.6 on 2023-10-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0001_initial"),
        ("teams", "0001_initial"),
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="teams",
            field=models.ManyToManyField(related_name="lead_teams", to="teams.teams"),
        ),
        migrations.AddField(
            model_name="company",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="userprofile.org",
            ),
        ),
    ]
