# Generated by Django 4.2.6 on 2023-10-17 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_useraddress_country'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneraddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.country', verbose_name='Country'),
        ),
    ]
