# Generated by Django 4.2.6 on 2023-10-17 15:32

import creme.creme_core.core.utils
import creme.creme_core.models.fields.autoslugfield
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0002_alter_attributeoption_options_and_more'),
        ('partner', '0002_alter_partneraddress_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('name', 'code'), 'permissions': (('dashboard_access', 'Can access dashboard'),), 'verbose_name': 'Đối tác hoàn thành', 'verbose_name_plural': 'Các đối tác hoàn thành'},
        ),
        migrations.AlterModelOptions(
            name='stockalert',
            options={'ordering': ('-date_created',), 'verbose_name': 'Thông báo tồn kho', 'verbose_name_plural': 'Những thông báo tồn kho'},
        ),
        migrations.AlterModelOptions(
            name='stockrecord',
            options={'verbose_name': 'Ghi lại tồn kho', 'verbose_name_plural': 'Bản ghi lưu kho '},
        ),
        migrations.AlterField(
            model_name='partner',
            name='code',
            field=creme.creme_core.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=128, populate_from='name', unique=True, verbose_name='Mã '),
        ),
        migrations.AlterField(
            model_name='partner',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='partners', to=settings.AUTH_USER_MODEL, verbose_name='Người sử dụng '),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày đóng'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='date_created',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Ngày tạo '),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='status',
            field=models.CharField(choices=[('Open', 'Mở'), ('Closed', 'Đóng ')], default='Open', max_length=128, verbose_name='Trạng thái '),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='stockrecord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='partner.stockrecord', verbose_name='Ghi lại tồn kho'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='threshold',
            field=models.PositiveIntegerField(verbose_name='Ngưỡng'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Ngày cập nhật '),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ngưỡng tồn kho thấp'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='num_allocated',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số phân bổ'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='num_in_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Số tồn kho'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockrecords', to='partner.partner', verbose_name='Đối tác'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='partner_sku',
            field=models.CharField(max_length=128, verbose_name='Đối tác SKU '),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='price_currency',
            field=models.CharField(default=creme.creme_core.core.utils.get_default_currency, max_length=12, verbose_name='Tiền tệ'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockrecords', to='catalogue.product', verbose_name='Sản phẩm'),
        ),
    ]
