# Generated by Django 4.2.6 on 2023-10-13 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.PERSONS_ORGANISATION_MODEL),
        migrations.swappable_dependency(settings.PERSONS_CONTACT_MODEL),
        ("emails", "0001_initial"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglist",
            name="contacts",
            field=models.ManyToManyField(
                editable=False,
                to=settings.PERSONS_CONTACT_MODEL,
                verbose_name="Contact-recipients",
            ),
        ),
        migrations.AddField(
            model_name="mailinglist",
            name="organisations",
            field=models.ManyToManyField(
                editable=False,
                to=settings.PERSONS_ORGANISATION_MODEL,
                verbose_name="Organisations recipients",
            ),
        ),
        migrations.AddField(
            model_name="entityemail",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, to="documents.document", verbose_name="Attachments"
            ),
        ),
        migrations.AddField(
            model_name="entityemail",
            name="signature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="emails.emailsignature",
                verbose_name="Signature",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, to="documents.document", verbose_name="Attachments"
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="signature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="emails.emailsignature",
                verbose_name="Signature",
            ),
        ),
        migrations.AddField(
            model_name="emailcampaign",
            name="mailing_lists",
            field=models.ManyToManyField(
                blank=True,
                to=settings.EMAILS_MLIST_MODEL,
                verbose_name="Related mailing lists",
            ),
        ),
    ]
