# Generated by Django 4.2.6 on 2023-10-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_email_id_alter_emailrecipient_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='from_email',
        ),
        migrations.RemoveField(
            model_name='email',
            name='message',
        ),
        migrations.RemoveField(
            model_name='email',
            name='send_time',
        ),
        migrations.RemoveField(
            model_name='email',
            name='to_email',
        ),
        migrations.AddField(
            model_name='email',
            name='body',
            field=models.TextField(blank=True, verbose_name='Sản phẩm '),
        ),
        migrations.AddField(
            model_name='email',
            name='reads',
            field=models.PositiveIntegerField(default=0, editable=False, null=True, verbose_name='Number of reads'),
        ),
        migrations.AddField(
            model_name='email',
            name='reception_date',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Reception date'),
        ),
        migrations.AddField(
            model_name='email',
            name='recipient',
            field=models.CharField(blank=True, max_length=100, verbose_name='Recipient'),
        ),
        migrations.AddField(
            model_name='email',
            name='sender',
            field=models.CharField(blank=True, max_length=100, verbose_name='Người gửi'),
        ),
        migrations.AddField(
            model_name='email',
            name='sending_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Sending date'),
        ),
        migrations.AddField(
            model_name='entityemail',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='entityemail',
            name='important',
            field=models.BooleanField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='lightweightemail',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='lightweightemail',
            name='important',
            field=models.BooleanField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sent'), (2, 'Not sent'), (3, 'Sending error'), (4, 'Synchronized')], default=2, editable=False, verbose_name='Trạng thái '),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chủ đề '),
        ),
        migrations.AlterField(
            model_name='emailsending',
            name='body',
            field=models.TextField(editable=False, verbose_name='Sản phẩm '),
        ),
        migrations.AlterField(
            model_name='emailsending',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Done'), (2, 'Trong tiến trình'), (3, 'Planned'), (4, 'Error during sending')], default=3, editable=False, verbose_name='Sending state'),
        ),
        migrations.AlterField(
            model_name='emailsending',
            name='subject',
            field=models.CharField(editable=False, max_length=100, verbose_name='Chủ đề '),
        ),
        migrations.AlterField(
            model_name='emailsendingconfigitem',
            name='name',
            field=models.CharField(help_text='Name displayed to users when selecting a configuration', max_length=100, unique=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='emailsendingconfigitem',
            name='username',
            field=models.CharField(blank=True, help_text='Eg: me@mydomain.org', max_length=254, verbose_name='Tên người dùng'),
        ),
        migrations.AlterField(
            model_name='entityemail',
            name='body',
            field=models.TextField(blank=True, verbose_name='Sản phẩm '),
        ),
        migrations.AlterField(
            model_name='entityemail',
            name='recipient',
            field=models.CharField(blank=True, max_length=100, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='entityemail',
            name='sender',
            field=models.CharField(blank=True, max_length=100, verbose_name='Người gửi'),
        ),
        migrations.AlterField(
            model_name='entityemail',
            name='sending_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Sending date'),
        ),
        migrations.AlterField(
            model_name='entityemail',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sent'), (2, 'Not sent'), (3, 'Sending error'), (4, 'Synchronized')], default=2, editable=False, verbose_name='Trạng thái '),
        ),
        migrations.AlterField(
            model_name='entityemail',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chủ đề '),
        ),
        migrations.AlterField(
            model_name='lightweightemail',
            name='body',
            field=models.TextField(blank=True, verbose_name='Sản phẩm '),
        ),
        migrations.AlterField(
            model_name='lightweightemail',
            name='recipient',
            field=models.CharField(blank=True, max_length=100, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='lightweightemail',
            name='sender',
            field=models.CharField(blank=True, max_length=100, verbose_name='Người gửi'),
        ),
        migrations.AlterField(
            model_name='lightweightemail',
            name='sending_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Sending date'),
        ),
        migrations.AlterField(
            model_name='lightweightemail',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sent'), (2, 'Not sent'), (3, 'Sending error'), (4, 'Synchronized')], default=2, editable=False, verbose_name='Trạng thái '),
        ),
        migrations.AlterField(
            model_name='lightweightemail',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chủ đề '),
        ),
    ]
