# Generated by Django 4.2.6 on 2023-10-13 14:33

import creme.creme_core.models.deletion
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creme_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_custom", models.BooleanField(default=True)),
                ("extra_data", models.JSONField(default=dict, editable=False)),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Type of event",
                "verbose_name_plural": "Types of event",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "cremeentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="creme_core.cremeentity",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "place",
                    models.CharField(blank=True, max_length=100, verbose_name="Place"),
                ),
                ("start_date", models.DateTimeField(verbose_name="Start date")),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End date"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Budget (€)",
                    ),
                ),
                (
                    "final_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Final cost (€)",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=creme.creme_core.models.deletion.CREME_REPLACE,
                        to="events.eventtype",
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ("name",),
                "abstract": False,
                "swappable": "EVENTS_EVENT_MODEL",
            },
            bases=("creme_core.cremeentity",),
        ),
    ]
