# Generated by Django 4.2.6 on 2023-10-13 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OverallRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.IntegerField(db_index=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, max_digits=6, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exposure", "app.Model-exposure"),
                            ("framing", "app.Model-framing"),
                            ("saturation", "app.Model-saturation"),
                            ("grammar", "app.Model2-grammar"),
                            ("complete", "app.Model2-complete"),
                            ("compelling", "app.Model2-compelling"),
                        ],
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("object_id", "content_type", "category")},
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.IntegerField(db_index=True)),
                ("rating", models.IntegerField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exposure", "app.Model-exposure"),
                            ("framing", "app.Model-framing"),
                            ("saturation", "app.Model-saturation"),
                            ("grammar", "app.Model2-grammar"),
                            ("complete", "app.Model2-complete"),
                            ("compelling", "app.Model2-compelling"),
                        ],
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "overall_rating",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="ratings.overallrating",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("object_id", "content_type", "user", "category")},
            },
        ),
    ]
