# Generated by Django 4.2.6 on 2023-10-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitinglist', '0002_alter_survey_id_alter_surveyanswer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglistentry',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Địa chỉ email '),
        ),
    ]
