# Generated by Django 4.2.6 on 2023-10-17 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('address', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('partner', '0001_initial'),
        ('communication', '0001_initial'),
    ]

    operations = [
    ]
