# Generated by Django 4.2.6 on 2023-10-17 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('partner', '0001_initial'),
        ('order', '0002_initial'),
    ]

    operations = [
    ]
