# Generated by Django 4.2.6 on 2023-10-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0002_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="teams",
            field=models.ManyToManyField(
                related_name="contact_teams", to="teams.teams"
            ),
        ),
    ]
