# Generated by Django 4.2.6 on 2023-10-13 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(blank=True, max_length=255)),
                ("website", models.CharField(blank=True, max_length=255)),
                ("object_id", models.IntegerField()),
                ("submit_date", models.DateTimeField(default=datetime.datetime.now)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("public", models.BooleanField(default=True)),
                ("comment", models.CharField(max_length=255)),
                ("commented_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment_Files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "comment_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comment_files",
                        verbose_name="File",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comments.comment",
                    ),
                ),
            ],
        ),
    ]
