# Generated by Django 4.2.6 on 2023-10-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="teams",
            field=models.ManyToManyField(related_name="tasks_teams", to="teams.teams"),
        ),
    ]
